#!/bin/bash

# Usage `curl https://raw.githubusercontent.com/Memristor-Robotics/mep-master/master/install | sh`

# Install Node.js
if [ -f "/etc/arch-release" ]; then
    sudo pacman -S nodejs npm --noconfirm
    sudo pacman -S git --noconfirm
else
    curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
    sudo apt install -y nodejs
    sudo apt install -y git
fi

# Install global Node.js modules
sudo npm install -g mocha node-gyp

# Clone the repo
git clone https://github.com/Memristor-Robotics/mep-master.git --depth 1
cd mep-master

# Install dependencies
npm install

# Test
npm test