#!/bin/bash

if [ "$1" != "--only-native" ]; then
    # Install npm global dependencies
    npm install -g jsdoc mocha node-gyp

    # Install npm dependencies
    npm install
fi

# Install native add-ons
node-gyp configure --directory src/drivers/modbus
node-gyp build --directory src/drivers/modbus

node-gyp configure --directory src/drivers/motion
node-gyp build --directory src/drivers/motion

node-gyp configure --directory src/services/terrain/pathfinding
node-gyp build --directory src/services/terrain/pathfinding

# Run tests to check of everything is OK
npm test