#!/bin/bash

SHOW_LOGO=true
PERFORMANCE=false
PERFORMANCE_PREFIX=
INTERACTIVE=false

for arg in $@; do
    # Turn on performance if there is `-p` or `--performance` flag
    if [ ${arg} = "-p" ] || [ ${arg} = "--performance" ]; then
        PERFORMANCE=true
    fi

    # Turn on interactive mode if there is `-i` or `--interactive` flag
    if [ ${arg} = "-i" ] || [ ${arg} = "--interactive" ]; then
        INTERACTIVE=true
    fi
done

# Generated with `figlet`
if [ $SHOW_LOGO = true ]; then
    echo " __  __                     _     _"
    echo "|  \/  | ___ _ __ ___  _ __(_)___| |_ ___  _ __"
    echo "| |\/| |/ _ \ |_   _ \| |__| / __| __/ _ \|  __|"
    echo "| |  | |  __/ | | | | | |  | \__ \ || (_) | |"
    echo "|_|  |_|\___|_| |_| |_|_|  |_|___/\__\___/|_|"
    echo ""
fi

# If interactive mode is active just run it
if [ $INTERACTIVE = true ]; then
    node --harmony-async-await -i -e 'require("./src/Bootstrap.js"); const TunedPoint = Mep.require("strategy/TunedPoint");'
    exit
fi

# Apply performance
if [ $PERFORMANCE = true ]; then
    export NODE_ENV=production

    if [ "$EUID" -ne 0 ]; then
        echo "Please run as root to turn on process privileges"
    else
        PERFORMANCE_PREFIX="nice -n -20 "
    fi
fi
${PERFORMANCE_PREFIX} node --harmony-async-await --nolazy src/Bootstrap.js "$@"

