#!/bin/bash

SHOW_LOGO=false

# Generated with `figlet`
if [ $SHOW_LOGO = true ]; then
    echo " __  __                     _     _"
    echo "|  \/  | ___ _ __ ___  _ __(_)___| |_ ___  _ __"
    echo "| |\/| |/ _ \ |_   _ \| |__| / __| __/ _ \|  __|"
    echo "| |  | |  __/ | | | | | |  | \__ \ || (_) | |"
    echo "|_|  |_|\___|_| |_| |_|_|  |_|___/\__\___/|_|"
    echo ""
fi

node src/Bootstrap.js "$@"
